// Code generated by go-swagger; DO NOT EDIT.

// Package restapi hello-world-plugin
//
//	Hello world plugin API.
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
