// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Hello world plugin API.",
    "title": "hello-world-plugin",
    "version": "0.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "operationId": "defaultPage",
        "responses": {
          "301": {
            "description": "Move to the default endpoint"
          }
        }
      }
    },
    "/api/expe": {
      "put": {
        "produces": [
          "application/json"
        ],
        "operationId": "expe",
        "parameters": [
          {
            "type": "string",
            "name": "name",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Greeting content.",
            "schema": {
              "type": "object",
              "required": [
                "message"
              ],
              "properties": {
                "message": {
                  "type": "string",
                  "x-nullable": false
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error - The server has encountered a situation it does not know how to handle."
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Hello world plugin API.",
    "title": "hello-world-plugin",
    "version": "0.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "operationId": "defaultPage",
        "responses": {
          "301": {
            "description": "Move to the default endpoint"
          }
        }
      }
    },
    "/api/expe": {
      "put": {
        "produces": [
          "application/json"
        ],
        "operationId": "expe",
        "parameters": [
          {
            "type": "string",
            "name": "name",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Greeting content.",
            "schema": {
              "type": "object",
              "required": [
                "message"
              ],
              "properties": {
                "message": {
                  "type": "string",
                  "x-nullable": false
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error - The server has encountered a situation it does not know how to handle."
          }
        }
      }
    }
  }
}`))
}
