// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ExpeOKCode is the HTTP code returned for type ExpeOK
const ExpeOKCode int = 200

/*
ExpeOK Greeting content.

swagger:response expeOK
*/
type ExpeOK struct {

	/*
	  In: Body
	*/
	Payload *ExpeOKBody `json:"body,omitempty"`
}

// NewExpeOK creates ExpeOK with default headers values
func NewExpeOK() *ExpeOK {

	return &ExpeOK{}
}

// WithPayload adds the payload to the expe o k response
func (o *ExpeOK) WithPayload(payload *ExpeOKBody) *ExpeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the expe o k response
func (o *ExpeOK) SetPayload(payload *ExpeOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExpeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ExpeInternalServerErrorCode is the HTTP code returned for type ExpeInternalServerError
const ExpeInternalServerErrorCode int = 500

/*
ExpeInternalServerError Internal Server Error - The server has encountered a situation it does not know how to handle.

swagger:response expeInternalServerError
*/
type ExpeInternalServerError struct {
}

// NewExpeInternalServerError creates ExpeInternalServerError with default headers values
func NewExpeInternalServerError() *ExpeInternalServerError {

	return &ExpeInternalServerError{}
}

// WriteResponse to the client
func (o *ExpeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
