consumes:
  - application/json
info:
  description: Hello world plugin API.
  title: hello-world-plugin
  version: 0.0.0
produces:
  - application/json
schemes:
  - http
swagger: "2.0"
paths:
  /:
    get:
      operationId: defaultPage
      responses:
        "301":
          description: Move to the default endpoint
  /api/expe:
    put:
      operationId: expe
      parameters:
        - in: query
          name: name
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Greeting content.
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                x-nullable: false
        "500":
          description: Internal Server Error - The server has encountered a situation it does not know how to handle.
